-- Standalone Expense workflow
-- Decouples Expense from Timesheet and adds full submit/approve/reject lifecycle.
-- Existing expense rows are deleted (they were tied to timesheets; staging data
-- will be regenerated by the seed script after this migration).

-- 1. Drop existing expenses (data loss is acceptable — staging only)
DELETE FROM "Expense";

-- 2. Drop old foreign key and column
ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS "Expense_timesheetId_fkey";
ALTER TABLE "Expense" DROP COLUMN IF EXISTS "timesheetId";

-- 3. Add new columns
ALTER TABLE "Expense"
  ADD COLUMN "employeeId"  TEXT        NOT NULL DEFAULT '',
  ADD COLUMN "projectId"   TEXT,
  ADD COLUMN "status"      TEXT        NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN "submittedAt" TIMESTAMP(3),
  ADD COLUMN "reviewedBy"  TEXT,
  ADD COLUMN "reviewNote"  TEXT,
  ADD COLUMN "reviewedAt"  TIMESTAMP(3),
  ADD COLUMN "updatedAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 4. Remove the temporary default on employeeId
ALTER TABLE "Expense" ALTER COLUMN "employeeId" DROP DEFAULT;

-- 5. Add foreign keys
ALTER TABLE "Expense"
  ADD CONSTRAINT "Expense_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Expense"
  ADD CONSTRAINT "Expense_projectId_fkey"
    FOREIGN KEY ("projectId") REFERENCES "Project"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

-- 6. Add expenses relation index
CREATE INDEX IF NOT EXISTS "Expense_employeeId_idx" ON "Expense"("employeeId");
CREATE INDEX IF NOT EXISTS "Expense_projectId_idx"  ON "Expense"("projectId");
